const errorDatabase = {
  "York": {
    "Wall": {
      "E1": "Room Senser เสียหรือชำรุด (เครื่องภายใน)",
      "E2": "Coil Senser เสียหรือชำรุด (เครื่องภายใน)",
      "E4": "แผงบอร์ดเสียหรือชำรุด",
      "E14": "มอเตอร์พัดลมภายใน เสียหรือชำรุด",
      "EF": "น้ำยารั่ว, น้ำยาขาด, น้ำยาน้อย",
      "E7": "การสื่อสารระหว่า FCU และ CDU ผิดพลาด",
      "F12": "EEPROM Outdoor เสียหรือชำรุด (เปลี่ยน PCB)",
      "F1": "IPM Module เสียหรือชำรุด (เปลี่ยน PCB)",
      "F22": "ระบบป้องกันกระแสเกินทำงาน",
      "F3": "การสื่อสารระหว่าง IPM และ Outdoor PCB ผิดปกติ",
      "F20": "ระบบป้องกันอุณหภูมิและแรงดันของ Compressor ทำงาน",
      "F19": "ระบบป้องกันแรงดันไฟฟ้าทำงาน (โวลต์ไฟฟ้าผิดปกติ)",
      "F4": "ระบบป้องกันอุณหภูมิที่ Dicharge ทำงาน",
      "F8": "มอเตอร์พัดลม DC Outdoor เสียหรือชำรุด",
      "F21": "Defrost Temp Senser ที่ Outdoor ทำงานหรือผิดปกติ",
      "F7": "Refrigerant Temp Sensor ที่ Compressor ทำงานผิดปกติ",
      "F6": "Outdoor Temp Sensor เสียหรือชำรุด",
      "F25": "Discharge Temp Sensor เสียหรือชำรุด",
      "F11": "Compressor ทำงานผิดปกติ",
      "F28": "Position Detection Circuit ทำงานผิดปกติ",
      "F2": "ระบบป้องกันกระแสเกินที่ Compressor ทำงาน",
      "F23": "ระบบป้องกัน Phase Current ทำงาน",
      "CL": "แจ้งเตือนการล้างแผ่นกรองอากาศ",
      "EC07": "เฟสไฟฟ้าระบบ 3 เฟสผิดปกติ หรือ แรงดันไฟฟ้าระบบ 1 เฟสผิดปกติ หรือมอเตอร์พัดลมของชุด CDU ทำงานผิดปกติ",
      "EC52": "Outdoor Temp Sensor เสียหรือชำรุด",
      "EH00": "EEPROM Indoor เสียหรือชำรุด (เปลี่ยน PCB)",
      "EH02": "การต่อสายสัญญาณหรือสายไฟผิดปกติ",
      "EH03": "มอเตอร์พัดลมภายใน เสียหรือชำรุด",
      "EH06": "การสื่อสารระหว่าง Indoor PCB และ Display Board ผิดปกติ",
      "EH60": "Room Senser เสียหรือชำรุด (เครื่องภายใน)",
      "EH61": "Room Senser เสียหรือชำรุด (เครื่องภายใน)",
      "EL01": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "EL0C": "Coil Senser เสียหรือชำรุด (เครื่องภายใน) หรือแอร์ทำความเย็นไม่ได้ หรือตรวจสอบระบบน้ำยา หรือพัดลม CDU ผิดปกติ",
      "Nf": "เปลี่ยนตัวกรอง (ไม่ใช่ข้อผิดพลาด)",
      "PC03": "แรงดันด้านสูงผิดปกติ ระบบอุดตันหรือคอนเดนเซอร์สกปรก",
      "SC": "ระบบทำความสะอาดตัวเอง (ไม่ใช่ข้อผิดพลาด)",
      "EA": "การสื่อสารระหว่าง Display board กับ Indoor control board มีปัญหา",
      "0": "ปกติ",
      "1": "Temp sensor ที่ ODU Coil มีปัญหา",
      "2": "Temp sensor ที่ Comp exhaust มีปัญหา",
      "5": "IPM Module เสียหรือชำรุด",
      "6": "ไฟ A/C module เสียหรือชำรุด",
      "7": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "8": "Current Overload ทำงาน",
      "9": "Maximum current ทำงาน",
      "10": "การสื่อสารระหว่าง ODU และ Driver ผิดพลาด",
      "11": "Outdoor EEPROM เสียหรือชำรุด",
      "12": "อุณหภูมิภายนอกสูงเกิน",
      "13": "อุณหภูมิสูงเกินที่ Comp exhaust",
      "14": "Outdoor ambient temp sensor เสียหรือชำรุด",
      "15": "อุณหภูมิสูงเกินที่ผิวของ Comp",
      "16": "Anti-freeze protection ทำงาน",
      "17": "PFC protection ทำงาน (driver pcb เสีย)",
      "18": "DC comp start protection ทำงาน (driver pcb เสีย)",
      "19": "Comp drive มีปัญหา",
      "20": "Outdoor fan motor มีปัญหา",
      "21": "Outdoor coil anti-overload ทำงาน (น้ำยาเกิน,ระบายไม่ออก,มอเตอร์ชำรุด,coil สกปรก)",
      "22": "Comp pre heating ทำงาน",
      "23": "แอร์รั่ว",
      "24": "Chip ที่ Outdoor board มีปัญหา",
      "26": "Overheated outdoor raditor มีปัญหา",
      "27": "High Pressure ทำงาน",
      "33": "Indoor room temp sensor เสียหรือชำรุด",
      "34": "IDU Coil temp sensor เสียหรือชำรุด",
      "36": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "38": "Indoor EEPROM เสียหรือชำรุด",
      "39": "Indoor fan motor เสียหรือชำรุด",
      "41": "ตัวป้องกัน IDU ลงกราวน์"
    },
    "Portable": {
      "P1": "ถังเก็บน้ำเต็ม นำถังเก็บน้ำไปเททิ้ง",
      "P2": "น้ำเต็มตัวเครื่อง ถอดปลั๊ก เทน้ำออก",
      "E1": "Room Senser เสียหรือชำรุด",
      "E2": "Coil Senser เสียหรือชำรุด (เครื่องภายใน)",
      "E3": "Coil Senser เสียหรือชำรุด (เครื่องภายนอก)",
      "E4": "EEPROM / PCB Board ชำรุด/ทำงานผิดปกติ",
      "E0": "ติดต่อศูนย์บริการ"
    },
    "Ceiling": {
      "E1": "Freeze Protection",
      "E5": "Indoor Fan Motor",
      "E6": "Cooling Fail",
      "E8": "Sensor Error"
    },
    "Ducted": {
      "E1": "Room Senser เสียหรือชำรุด",
      "E5": "คอมเพรสเซอร์มีปัญหา",
      "E6": "Low Pressure ทำงาน",
      "E8": "Sensor Error",
      "E2": "Coil Senser เสียหรือชำรุด (เครื่องภายใน)",
      "E3": "Coil Senser เสียหรือชำรุด (เครื่องภายนอก)",
      "E4": "ปริมาณน้ำยาไม่เพียงพอ, ระบบทำความเย็นไม่ได้",
      "E7": "High Pressure ทำงาน",
      "1": "AHU ไม่ทำงาน ให้เปิด-ปิด ระบบไฟใหม่ เพื่อเริ่มต้นระบบใหม่",
      "2": "Return Sensor ไม่ทำงาน/ชำรุด",
      "3": "Sensor Coil 1 ไม่ทำงาน/ชำรุด",
      "4": "Sensor Coil 2 ไม่ทำงาน/ชำรุด",
      "5": "Sensor Coil 3 ไม่ทำงาน/ชำรุด",
      "6": "Sensor Coil 4 ไม่ทำงาน/ชำรุด",
      "7": "ระบบป้องกันกำลังไฟของ CDU1 หรือพัดลม CDU1 หรือ High-Low Pressure 1 ทำงาน",
      "8": "Anti Freeze Coil 1",
      "9": "Circuit ที่ 1 ไม่เย็น",
      "10": "ระบบป้องกันกำลังไฟของ CDU2 หรือพัดลม CDU2 หรือ High-Low Pressure 2 ทำงาน",
      "11": "Anti Freeze Coil 2",
      "12": "Circuit ที่ 2 ไม่เย็น",
      "13": "ระบบป้องกันกำลังไฟของ CDU3 หรือพัดลม CDU3 หรือ High-Low Pressure 3 ทำงาน",
      "14": "Anti Freeze Coil 3",
      "15": "Circuit ที่ 3 ไม่เย็น",
      "16": "ระบบป้องกันกำลังไฟของ CDU4 หรือพัดลม CDU4 หรือ High-Low Pressure 4 ทำงาน",
      "17": "Anti Freeze Coil 4",
      "18": "Circuit ที่ 4 ไม่เย็น"
    },
    "Concealed": {
      "E1": "Freeze Protection",
      "E5": "Indoor Fan Motor",
      "E6": "Cooling Fail",
      "E8": "Sensor Error"
    },
    "Floor": {
      "E0": "Indoor EEPROM / PCB เสียหรือชำรุด",
      "E4": "Temp sensor ลมกลับ เสียหรือชำรุด",
      "E5": "Piping sensor FCU เสียหรือชำรุด",
      "Eb": "การสื่อสารระหว่าง PCB และ Display board ผิดพลาด หรือ PCB เสียหรือชำรุด",
      "EC": "น้ำยารั่ว/น้ำยาน้อย",
      "A": "Temp sensor ambient เสียหรือชำรุด",
      "F2": "Piping sensor CDU เสียหรือชำรุด",
      "P13": "Freezer sensor ป้องกันน้ำแข็งทำงาน"
    }
  },
  "Hitachi": {
    "Wall": {
      "2": "มีการฝืนการทำงานภายในชุด CDU",
      "5": "เพาเวอร์รีเลย์ชำรุด หรือเกิดการเสียหาย",
      "10": "มีกระแสเกินใน DC มอเตอร์ของชุด FCU",
      "13": "IC521 หรือ IC401 ทำงานผิดปกติหรือชำรุด (ตรวจเช็ค PCB)",
      "14": "IDU Coil temp sensor เสียหรือชำรุด",
      "15": "Indoor room temp sensor เสียหรือชำรุด",
      "3": "การเชื่อมต่อวงจรอิเล็กทรอนิกส์ภายในชุด FCU ผิดปกติ",
      "9": "Sensor วัดอุณหภูมิห้อง หรือ sensor Coil หรือ sensor วัดความชื้น เสียหรือชำรุด",
      "12": "การเชื่อมต่อวงจรอิเล็กทรอนิกส์ภายในชุด CDU ผิดปกติ"
    },
    "Cassette": {
      "1": "Outdoor ambient temp sensor เสียหรือชำรุด",
      "2": "Outdoor coil temp sensor เสียหรือชำรุด",
      "3": "Unit over current ทำงาน (เครื่องกินกระแสสูงเกิน)",
      "4": "EEPROM เสียหรือชำรุด",
      "5": "Cooling freezing protection (แผงคอยล์เย็นเป็นน้ำแข็ง)",
      "6": "Motor Blockage protection",
      "7": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "8": "Phase current ทำงาน",
      "9": "U Phase current ทำงานหรือผิดปกติ",
      "10": "V Phase current ทำงานหรือผิดปกติ",
      "11": "Phase ผิด",
      "12": "Voltage ขาดเฟส,สลับเฟส",
      "13": "Compressor overheat protector ทำงาน",
      "14": "เครื่องตัด High Pressure",
      "15": "เครื่องตัด Low Pressure",
      "16": "Overload protection ทำงาน",
      "17": "Discharge Temp Sensor เสียหรือชำรุด",
      "18": "AC Voltage ผิดปกติ",
      "19": "Suction Temp sensor เสียหรือชำรุด",
      "22": "Defrosting sensor เสียหรือชำรุด",
      "45": "Driver (IPM) เสียหรือชำรุด",
      "46": "การสื่อสารระหว่าง Driver และ Control board ผิดพลาดหรือชำรุด",
      "47": "Discharge Temp สูงเกิน",
      "48": "Outdoor DC Fan motor (ตัวบน)",
      "49": "Outdoor DC Fan motor (ตัวล่าง)",
      "91": "เครื่องไม่ทำงานเนื่องจาก IPM Board ร้อนสูงเกิน",
      "96": "น้ำยารั่ว/น้ำยาน้อย",
      "97": "4-Way valve communication เสียหรือชำรุด",
      "51": "Drainage protection น้ำในถาดน้ำสูงเกิน,ระบายน้ำทิ้งไม่ออก,ลูกลอยค้าง",
      "64": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "71": "Indoor unit zero check สายมอเตอร์หลวม/ขาด/ชำรุด,มอเตอร์เสีย,พัดลมหมุนกลับทาง",
      "72": "Indoor fan motor เสียหรือชำรุด สายมอเตอร์หลวม/ขาด/ชำรุด,มอเตอร์เสีย,PCB เสีย",
      "73": "FCU EEPROM data 1 เสียหรือชำรุด",
      "74": "FCU EEPROM data 2 เสียหรือชำรุด",
      "81": "FCU ambient temp sensor เสียหรือชำรุด",
      "83": "Evaporator middle temp sensor เสียหรือชำรุด",
      "FE": "การสื่อสารระหว่าง Main control board กับ Remote มีสาย ผิดปกติ",
      "ER": "การสื่อสารระหว่าง Main control board กับ Display board ผิดปกติ"
    },
    "Ceiling": {
      "1": "Outdoor ambient temp sensor เสียหรือชำรุด",
      "2": "Outdoor coil temp sensor เสียหรือชำรุด",
      "3": "Unit over current ทำงาน (เครื่องกินกระแสสูงเกิน)",
      "4": "EEPROM เสียหรือชำรุด",
      "5": "Cooling freezing protection (แผงคอยล์เย็นเป็นน้ำแข็ง)",
      "6": "Motor Blockage protection",
      "7": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "8": "Phase current ทำงาน",
      "9": "U Phase current ทำงานหรือผิดปกติ",
      "10": "V Phase current ทำงานหรือผิดปกติ",
      "11": "Phase ผิด",
      "12": "Voltage ขาดเฟส,สลับเฟส",
      "13": "Compressor overheat protector ทำงาน",
      "14": "เครื่องตัด High Pressure",
      "15": "เครื่องตัด Low Pressure",
      "16": "Overload protection ทำงาน",
      "17": "Discharge Temp Sensor เสียหรือชำรุด",
      "18": "AC Voltage ผิดปกติ",
      "19": "Suction Temp sensor เสียหรือชำรุด",
      "22": "Defrosting sensor เสียหรือชำรุด",
      "45": "Driver (IPM) เสียหรือชำรุด",
      "46": "การสื่อสารระหว่าง Driver และ Control board ผิดพลาดหรือชำรุด",
      "47": "Discharge Temp สูงเกิน",
      "48": "Outdoor DC Fan motor (ตัวบน)",
      "49": "Outdoor DC Fan motor (ตัวล่าง)",
      "91": "เครื่องไม่ทำงานเนื่องจาก IPM Board ร้อนสูงเกิน",
      "96": "น้ำยารั่ว/น้ำยาน้อย",
      "97": "4-Way valve communication เสียหรือชำรุด",
      "51": "Drainage protection น้ำในถาดน้ำสูงเกิน,ระบายน้ำทิ้งไม่ออก,ลูกลอยค้าง",
      "64": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "71": "Indoor unit zero check สายมอเตอร์หลวม/ขาด/ชำรุด,มอเตอร์เสีย,พัดลมหมุนกลับทาง",
      "72": "Indoor fan motor เสียหรือชำรุด สายมอเตอร์หลวม/ขาด/ชำรุด,มอเตอร์เสีย,PCB เสีย",
      "73": "FCU EEPROM data 1 เสียหรือชำรุด",
      "74": "FCU EEPROM data 2 เสียหรือชำรุด",
      "81": "FCU ambient temp sensor เสียหรือชำรุด",
      "83": "Evaporator middle temp sensor เสียหรือชำรุด",
      "FE": "การสื่อสารระหว่าง Main control board กับ Remote มีสาย ผิดปกติ",
      "ER": "การสื่อสารระหว่าง Main control board กับ Display board ผิดปกติ"
    },
    "Ducted": {
      "1": "Outdoor ambient temp sensor เสียหรือชำรุด",
      "2": "Outdoor coil temp sensor เสียหรือชำรุด",
      "3": "Unit over current ทำงาน (เครื่องกินกระแสสูงเกิน)",
      "4": "EEPROM เสียหรือชำรุด",
      "5": "Cooling freezing protection (แผงคอยล์เย็นเป็นน้ำแข็ง)",
      "6": "Motor Blockage protection",
      "7": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "8": "Phase current ทำงาน",
      "9": "U Phase current ทำงานหรือผิดปกติ",
      "10": "V Phase current ทำงานหรือผิดปกติ",
      "11": "Phase ผิด",
      "12": "Voltage ขาดเฟส,สลับเฟส",
      "13": "Compressor overheat protector ทำงาน",
      "14": "เครื่องตัด High Pressure",
      "15": "เครื่องตัด Low Pressure",
      "16": "Overload protection ทำงาน",
      "17": "Discharge Temp Sensor เสียหรือชำรุด",
      "18": "AC Voltage ผิดปกติ",
      "19": "Suction Temp sensor เสียหรือชำรุด",
      "22": "Defrosting sensor เสียหรือชำรุด",
      "45": "Driver (IPM) เสียหรือชำรุด",
      "46": "การสื่อสารระหว่าง Driver และ Control board ผิดพลาดหรือชำรุด",
      "47": "Discharge Temp สูงเกิน",
      "48": "Outdoor DC Fan motor (ตัวบน)",
      "49": "Outdoor DC Fan motor (ตัวล่าง)",
      "91": "เครื่องไม่ทำงานเนื่องจาก IPM Board ร้อนสูงเกิน",
      "96": "น้ำยารั่ว/น้ำยาน้อย",
      "97": "4-Way valve communication เสียหรือชำรุด",
      "51": "Drainage protection น้ำในถาดน้ำสูงเกิน,ระบายน้ำทิ้งไม่ออก,ลูกลอยค้าง",
      "64": "การสื่อสารระหว่าง FCU และ CDU ผิดพลาด",
      "71": "Indoor unit zero check สายมอเตอร์หลวม/ขาด/ชำรุด,มอเตอร์เสีย,พัดลมหมุนกลับทาง",
      "72": "Indoor fan motor เสียหรือชำรุด สายมอเตอร์หลวม/ขาด/ชำรุด,มอเตอร์เสีย,PCB เสีย",
      "73": "FCU EEPROM data 1 เสียหรือชำรุด",
      "74": "FCU EEPROM data 2 เสียหรือชำรุด",
      "81": "FCU ambient temp sensor เสียหรือชำรุด",
      "83": "Evaporator middle temp sensor เสียหรือชำรุด",
      "FE": "การสื่อสารระหว่าง Main control board กับ Remote มีสาย ผิดปกติ",
      "ER": "การสื่อสารระหว่าง Main control board กับ Display board ผิดปกติ"
    }
  }
};
